import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NotificationBell } from "@/components/NotificationBell";
import { CommandMenu } from "@/components/CommandMenu";
import { ApiKeySettings } from "@/components/ApiKeySettings";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <body className="min-h-full flex flex-col font-body bg-background text-foreground">
        <div className="min-h-screen flex flex-col newsprint-texture">
          <header className="bg-background border-b border-border py-6 px-6 flex justify-between items-center relative z-40">
            <h1 className="text-foreground font-serif font-black text-4xl tracking-tighter uppercase">The NotMoodle</h1>
            <div className="flex items-center gap-4">
              <span className="text-xs text-foreground font-mono uppercase tracking-widest hidden sm:inline-block border border-border px-3 py-1 bg-muted">Edition: Vol 1.0</span>
              <ApiKeySettings />
              <NotificationBell />
            </div>
          </header>
          <div className="flex-1">
            {children}
          </div>
        </div>
        <CommandMenu />
      </body>
    </html>
  );
}
