import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NotificationBell } from "@/components/NotificationBell";
import { CommandMenu } from "@/components/CommandMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="min-h-screen bg-gray-900 flex flex-col">
          <header className="bg-gray-800 border-b border-gray-700 py-4 px-6 flex justify-between items-center">
            <h1 className="text-white font-bold text-xl">NotMoodle</h1>
            <div className="flex items-center gap-4">
              <span className="text-sm text-gray-400 hidden sm:inline-block border border-gray-700 rounded px-2 py-1">Cmd+K</span>
              <NotificationBell />
            </div>
          </header>
          <div className="flex-1">
            {children}
          </div>
        </div>
        <CommandMenu />
      </body>
    </html>
  );
}
